AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Description: sasha

Parameters:
  ApplicationName:
    Description: resource prefix
    Type: String
    Default: sasha
  ScheduleExpression:
    Description: schedule expression for the eventbridge event
    Type: String
    Default: rate(3 hours)
  DaysToRetainLogs:
    Description: days to retain logs in CloudWatch
    Type: Number
    Default: 30
  PagesToScrape:
    Description: pages to scrape matches
    Type: Number
    Default: 6
  MaxConcurrency:
    Description: concurrency of scrape pages
    Type: Number
    Default: 1
  # ScrapingIntervalSeconds:
  #   Description: interval seconds to start scraping the next page
  #   Type: Number
  #   Default: 900

Resources:
  SashaStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${ApplicationName}-state-machine
      DefinitionUri: statemachine/scraping.asl.json
      DefinitionSubstitutions:
        PagesToScrape: !Ref PagesToScrape
        # ScrapingIntervalSeconds: !Ref ScrapingIntervalSeconds
        SashaFunctionArn: !GetAtt SashaFunction.Arn
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroup.Arn
        IncludeExecutionData: true
        Level: ALL
      Role: !GetAtt StepFunctionRole.Arn
      Events:
        Schedule:
          Type: ScheduleV2
          Properties:
            Name: !Sub ${ApplicationName}-state-machine-scheduler
            ScheduleExpression: !Ref ScheduleExpression

  RequestsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${ApplicationName}-requests
      ContentUri: layer/requests/
      CompatibleRuntimes:
        - python3.11
        - python3.12
    Metadata:
      BuildMethod: python3.12

  SelectolaxLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${ApplicationName}-selectolax
      ContentUri: layer/selectolax/
      CompatibleRuntimes:
        - python3.11
        - python3.12
    Metadata:
      BuildMethod: python3.12

  PythonDateutilLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${ApplicationName}-python-dateutil
      ContentUri: layer/python-dateutil/
      CompatibleRuntimes:
        - python3.11
        - python3.12
    Metadata:
      BuildMethod: python3.12

  SashaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ApplicationName}-scraper
      CodeUri: functions/sasha/
      Description: "scrape vlr.gg upcoming matches"
      Handler: index.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 900
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref VlrMatchesTable
      Environment:
        Variables:
          VLR_MATCHES_TABLE: !Ref VlrMatchesTable
      Layers:
        - !Ref RequestsLayer
        - !Ref SelectolaxLayer
        - !Ref PythonDateutilLayer

  VlrMatchesTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub ${ApplicationName}-vlr-matches
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
        - AttributeName: startDate
          AttributeType: S
      BillingMode: PROVISIONED
      DeletionProtectionEnabled: True
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: startDate
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/states/${ApplicationName}-state-machine
      RetentionInDays: !Ref DaysToRetainLogs

  SashaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SashaFunction}
      RetentionInDays: !Ref DaysToRetainLogs

  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ApplicationName}-stepfunctions-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - "sts:AssumeRole"

  StepFunctionsLoggingPolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: !Sub ${ApplicationName}-stepfunctions-policy
      RoleName: !Ref StepFunctionRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: !Sub "${SashaFunction.Arn}*"
          - Effect: Allow
            Action:
              - logs:CreateLogDelivery
              - logs:CreateLogStream
              - logs:GetLogDelivery
              - logs:UpdateLogDelivery
              - logs:DeleteLogDelivery
              - logs:ListLogDeliveries
              - logs:PutLogEvents
              - logs:PutResourcePolicy
              - logs:DescribeResourcePolicies
              - logs:DescribeLogGroups
            Resource: "*"

Outputs:
  VlrMatchesTableName:
    Description: DynamoDB Table for match list
    Value: !Ref VlrMatchesTable
